repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]

  # Security scanning
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.10
    hooks:
      - id: bandit
        args: ['-x', 'tests', '-s', 'B105,B311']
        exclude: ^tests/

  # Python modernization
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.18.0
    hooks:
      - id: pyupgrade
        args: [--py3-only, --py38-plus]

  # Odoo-specific hooks
  - repo: https://github.com/OCA/odoo-pre-commit-hooks
    rev: v0.1.4
    hooks:
      - id: oca-checks-odoo-module
        args: ['--disable=xml-deprecated-data-node']
      - id: oca-checks-po
        args: ["--fix"]

  # Pylint with Odoo plugin (disabled for now - has many warnings to fix)
  # - repo: https://github.com/OCA/pylint-odoo
  #   rev: v9.3.12
  #   hooks:
  #     - id: pylint_odoo
  #       args: ["--rcfile=.pylintrc", "--load-plugins=pylint_odoo"]

  - repo: https://github.com/OCA/pylint-odoo
    rev: v9.3.12 # may be a tag or commit hash
    hooks:
      # Add to your .pylintrc file:
      # [MASTER]
      # load-plugins=pylint_odoo
      - id: pylint_odoo
